framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                # dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                dsn: '%env(RABBITMQ_URL)%'
                # options:
                #     use_notify: true
                #     check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            queuing: 'in-memory:///'
            # sync: 'sync://'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            App\Message\NewUserMessage: async
            JoliCode\Elastically\Messenger\MultipleIndexationRequest: async
            JoliCode\Elastically\Messenger\IndexationRequest: queuing
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
