version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: myprojects
      MYSQL_USER: mn_root
      MYSQL_PASSWORD: mn_toor

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor # ignore vendor map
    depends_on:
      - db
      - rabbitmq
      - minio
    environment:
      - NODE_VERSION=16
      - SYMFONY_ENV=dev

  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: your_rabbitmq_user
      RABBITMQ_DEFAULT_PASS: your_rabbitmq_password

  minio:
    image: minio/minio:latest
    command: server /data
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: your_minio_user
      MINIO_ROOT_PASSWORD: your_minio_password
    volumes:
      - minio_data:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - '8080:80'
    depends_on:
      - db

volumes:
  minio_data:
