FROM php:8.2-apache

WORKDIR /var/www/html

RUN apt-get update \
    && apt-get install -y \
        zlib1g-dev \
        libzip-dev \
        unzip \
    && docker-php-ext-install zip pdo_mysql \
    && a2enmod rewrite

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Configuration personnalisée pour Apache
COPY apache.conf /etc/apache2/sites-available/000-default.conf
