version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: myprojects
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html

  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: your_rabbitmq_user
      RABBITMQ_DEFAULT_PASS: your_rabbitmq_password

  minio:
    image: minio/minio:latest
    command: server /data
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: your_minio_user
      MINIO_ROOT_PASSWORD: your_minio_password
    volumes:
      - minio_data:/data

  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
volumes:
  minio_data:
