FROM php:7.4-apache

WORKDIR /var/www/html

RUN apt-get update \
    && apt-get install -y \
        zlib1g-dev \
        libzip-dev \
        unzip \
    && docker-php-ext-install zip pdo_mysql \
    && a2enmod rewrite
