name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-publish-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Set Lowercase Repository Name
        id: lowercase-repo
        run: echo "::set-output name=repository::$(echo ${{ github.repository }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Build and Publish Docker image 
        run: |
          docker buildx create --use
          docker buildx build --push --tag ghcr.io/${{ steps.lowercase-repo.outputs.repository }}:latest .
