name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set Lowercase Repository Name
      id: lowercase-repo
      run: echo "::set-output name=repository::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"

    - name: Build and push Docker image
      run: |
        docker build -t myprojects .
        docker tag myprojects:latest ghcr.io/${{ steps.lowercase-repo.outputs.repository }}/myprojects:latest
        docker push ghcr.io/${{ steps.lowercase-repo.outputs.repository }}/myprojects:latest

    - name: SSH to server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          docker-compose -f docker-compose.prod.yml up -d
